### ISSUE TITLE
Guides: behavior tweaks

### ISSUE THREAD

**Issue by kissane** [OpenNews/opennews-source#25]
@ryanpitts, I dug this up while excavating old editorial issues—we'd talked about adding two additional credit fields in the Guide admin page in the CMS (the one for making new guides):

- A field for adding an author credit for non-staff-written Guides
- A field for each link entry that allows us to list the author and org for non-Source pieces that we link to
- I suppose also maybe we want to pull the photo and bio of the author for non-staff Guides? 

I dunno if this stuff can make it into the next release, but let's put them on the board for sometime.

**Comment by ryanpitts** [comment]
Yep, should be able to fit this in. So would add these three to the primary Guide model:
* `author_name`
* `author_bio`
* `author_photo`

For the links, do you just want one unified `external_credit` field, or separate `author_name` and `organization_name` fields? (I'd normally split into two fields here, but I don't feel strongly.)

**Comment by kissane** [comment]
Yes, please! And I would prefer to split into two fields for author and org, and ideally to make them both optional, please.

**Comment by ryanpitts** [comment]
Awesome, will do. I don't think either of the Guide templates (list or detail) is on @beep's list, correct?

**Comment by beep** [comment]
@ryanpitts Not currently! The only Guide-related wireframe I’ve seen, I think, is the one for the [submit a guide page](https://wireframe.cc/IQiFwU). (Which could easily be built out of the [submit a repo page](https://wireframe.cc/6mChAO) I’m finishing up.)

Are there wireframes for the list or detail Guide pages you mentioned? I can see if they’ll be covered by modules in the existing pages I’m working on.

**Comment by kissane** [comment]
Newp, no Guides on @beep's list. I don't remember now why we didn't wireframe it, but @ryanpitts, I could do one for you if that would be helpful. It's a pretty straightforward page, so I feel like we'd be able to assemble it from Marcotted™ modules…?

**Comment by ryanpitts** [comment]
Yep, I imagine the "Featured Repos" section of the code landing page translates pretty well into the guides landing page?

**Comment by kissane** [comment]
Yeah, I think so.

**Comment by ryanpitts** [comment]
OK, so pushing this one out uncovers a couple questions. Here's an initial template: https://opennews-source-staging.herokuapp.com/guides/

* Looks like when there's no `content-aside` column at right on the page, the main module is free to keep expanding. If there's an appropriate aside for this page, we should totally add it, but flagging this in case there are pages where we won't have anything at right.
* What would an appropriate aside be? Handful of recent articles?
* I pulled this from the "Featured Repos" module on the Code page, which has `flex-wrap: nowrap` because there would only ever be three items. On this page, we'll need a wrap -- not sure what the appropriate setting will end up being there, because `flex-wrap: wrap` justifies the last column.

cc @kissane @beep

**Comment by beep** [comment]
> Looks like when there's no content-aside column at right on the page, the main module is free to keep expanding. If there's an appropriate aside for this page, we should totally add it, but flagging this in case there are pages where we won't have anything at right.

Good catch, @ryanpitts. The 8-templates branch already has an outer constraint on `.page`, but I’ve just added one for `.content-main`—it’s now capped at `60em`.

> I pulled this from the "Featured Repos" module on the Code page, which has flex-wrap: nowrap because there would only ever be three items. On this page, we'll need a wrap -- not sure what the appropriate setting will end up being there, because flex-wrap: wrap justifies the last column.

Yeah, that’s a bug on my part, which is _also_ fixed in the #8 branch. (https://github.com/OpenNews/opennews-source/commit/f6ff0407ebee37ddc8f06d08153281b460aaafd4#diff-1c338323ce1d4a0d2009c0d6a0acd801L1005) Tossed in a justification fix for the list, too. (6b652d21b8d958861fd3ffb06409db836c856de9)

Thanks, Ryan!

**Comment by ryanpitts** [comment]
sweeeeeet. I've been avoiding merging from that branch in-progress -- does it seem safe to pull from now?

**Comment by beep** [comment]
@ryanpitts I’m still workin’ on it, but if you’d like to, sure! (I’m hoping to push a raft of layout/browser fixes soon, as well as the new templates. More anon.)

**Comment by ryanpitts** [comment]
@beep we've got a longish staff call kicking up here in about half an hour, so no reason at all for me to pull anything if you're still working. Will wait until you give the high sign.

**Comment by beep** [comment]
Awesome, @ryanpitts—thanks!

I’m trying to smooth out a final IE9 issue (this is a matter of personal pride), then I’ll open a PR.

**Comment by ryanpitts** [comment]
This feels maybe ok to close? The new `author_name` and `author_bio` fields are in place and show up on the templates when used. We don't show `author_photo` yet, but seems like that's a design question we can revisit after launch.
