### ISSUE TITLE
Django templates: add OG tags

### ISSUE THREAD

**Issue by ryanpitts** [OpenNews/opennews-source#29]
OK, mostly cribbing off [this article](https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254#.jqyx958ci), I'll add this to the article template (and a modified version to other object templates).

```
<!-— facebook open graph tags -->
<meta property="og:type" content="website" />
<meta property="og:url" content="{{ request.build_absolute_uri() }}" />
<meta property="og:title" content="{{ article.title }}" />
<meta property="og:description" content="{{ article.subhead }}" />
<meta property="og:image" content="{{ MEDIA_URL }}{{ thumbnail(article.image, "1200") }}" />
 
<!-— twitter card tags additive with the og: tags -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:domain" value="{{ settings.BASE_SITE_URL }}" />
<meta name="twitter:title" value="{{ article.title }}" />
<meta name="twitter:description" value="{{ article.subhead }}" />
<meta name="twitter:image" content="{{ MEDIA_URL }}{{ thumbnail(article.image, "600") }}" />
<meta name="twitter:image:alt" content="{{ article.pretty_caption }}" />
<meta name="twitter:url" value="{{ request.build_absolute_uri() }}" />
<meta name="twitter:site" value="@source" />
```

Anything I'm missing, @beep? Are 1200 and 600 sane image sizes here?

**Comment by beep** [comment]
@ryanpitts I thiiiiiiiiiiiiink that’s totally fine! Twitter does require a minimum 120×120 size, but otherwise, I don’t think there’s any kind of upper limit. [Twitter’s “summary card”](https://dev.twitter.com/cards/types/summary) _will_ auto-crop non-square images to, uh, square, however.

(Also, there are some [length constraints](https://www.lullabot.com/articles/big-trouble-in-little-content-planning-for-reusable-microcopy)—not sure if you need to know/track those, though.)

**Comment by ryanpitts** [comment]
Yep, favoring the `subhead` attribute over any `summary`-type text blocks for those. Thanks!
