### ISSUE TITLE
Template integration: feedback on community_index template 

### ISSUE THREAD

**Issue by ryanpitts** [OpenNews/opennews-source#50]
This page is much closer to being fine. Same need as in https://github.com/OpenNews/opennews-source/issues/45 to fix the organization line underneath the people promos, but not a bad start: https://opennews-source-staging.herokuapp.com/community/

**Comment by beep** [comment]
> Same need as in #45 to fix the organization line underneath the people promos

Snuck a fix into #55 that should tackle this! 5ed33902fb15e6af4a28bdc868db5e6e8445ccfa

**Comment by beep** [comment]
@ryanpitts http://sourcedev.ethanmarcotte.com/tmpl/list-people.php is a new thing, and outlines a few changes that could help us out here. Namely:

- Since there’s only one entry per person, I’d recommend using a regular ol’ `<p class="has-icon icon-company">` for the company names on this page. (If we need more, then we could use a list; let me know if I can mock that up.)
- There’s some updated CSS that cleans up a few alignment fixes.

How’s that look/sound to you?

**Comment by ryanpitts** [comment]
Boom, looks great

![screen shot 2017-02-01 at 11 41 53 am](https://cloud.githubusercontent.com/assets/56477/22523235/78cadf3e-e873-11e6-87a5-af8e5aa97520.png)

**Comment by kissane** [comment]
I think we're closed here?

**Comment by ryanpitts** [comment]
Seems good to me -- I was going to leave these threads open until both you and @beep had checked off in https://github.com/OpenNews/opennews-source/issues/71

**Comment by kissane** [comment]
Fabulous.
