### ISSUE TITLE
Missing images—path problem?

### ISSUE THREAD

**Issue by kissane** [OpenNews/opennews-source#91]
I was just looking at some broken images on staging while Juna finished dinner, and noticed two things that may be causing some problems. 

* We still have the little piece of scripting in place that hides broken images in articles in some articles on staging, so the content audit Lindsay and I are doing will be incomplete. Is there any programmatic way to delete that so that we can see more clearly what's actually broken?
* A bunch of images seem to have broken between the old site and staging, I think because of an image storage path mismatch. For instance, in https://opennews-source-staging.herokuapp.com/admin/articles/article/255/change/, I'm seeing `/media/img/uploads/article_images/streamtools_fig1.png` in the markup, but `img/uploads/article_images/streamtools_fig3.png` as the actual image-storage location. I checked and that image is fine on old Source, so I think it's this discrepancy that's breaking them. I'll screenshot for extra clarity.

<img width="733" alt="screen shot 2017-02-06 at 8 00 50 pm" src="https://cloud.githubusercontent.com/assets/1910034/22673242/069d7ea2-eca7-11e6-8d86-610850c96265.png">

Much obliged for any assistance you can offer, @ryanpitts!

**Comment by ryanpitts** [comment]
1) Yep, I can run a db update that looks for that hacky bit of script that hides broken images and removes it. Will let you know once it's run.

2) Ah, this is an artifact of the way uploads used to be stored on the application server itself rather than being stored in a separate media location. So all inline article imgs pointing to places like `/media/img/uploads/article_images/streamtools_fig1.png` are looking for files at https://opennews-source-staging.herokuapp.com/media/img/uploads/article_images/streamtools_fig1.png, and need to be repointed to the new media.opennews.org location, like https://media.opennews.org/img/uploads/article_images/streamtools_fig1.png. Can also run a db update for this.

**Comment by kissane** [comment]
That would be awesome, many thanks! Doing it article-by-article would take more days than we have, I think.

**Comment by ryanpitts** [comment]
OK, since I already wrote scripts and ran them, let's go with the db update method then!

Should look better now: https://opennews-source-staging.herokuapp.com/articles/introducing-streamtools/

**Comment by kissane** [comment]
Fine, Ryan, just FIX it then, see if I care.

**Comment by kissane** [comment]
I think there might be a slight pattern variation to deal with, as I'm seeing some that still look like `https://source.opennews.org/media/img/uploads/article_images/smoking_gun.png` in articles like https://opennews-source-staging.herokuapp.com/admin/articles/article/254/change/ — it looks like we have the absolute path in some articles, I think maybe the ones Casey or Kio produced.

**Comment by ryanpitts** [comment]
OK, these patterns are all updated in the staging db

**Comment by kissane** [comment]
Tested and looking perfect, thanks! Closing.
